server {
         listen 80;
         listen [::]:80;
         root /var/www/html/;
         index index.html index.htm;
         server_name access-request-fulfilment.patient-deductions.nhs.uk;
         location / {
              try_files $uri $uri /index.html;
         }
}