events {
     worker_connections  4096;  ## Default: 1024
}
http {
     server {
     listen       80;
          location / {
               root   /usr/share/nginx/html;
               index  index.html index.htm;
               include /etc/nginx/mime.types;
               try_files $uri $uri/ /index.html$is_args$args;
          }
     }    
}

stream {
     server {
          listen 443;
          location /Auth/BackChannelLogout {
               proxy_ssl_server_name on;
               proxy_pass %DOC_STORE_API_ENDPOINT%/%BUILD_ENV%/Auth/BackChannelLogout;
               ssl_preread on;
          }
     }
}