events {
     worker_connections  4096;  ## Default: 1024
}
http {
     server {
     listen       80;
     server_name access-request-fulfilment.patient-deductions.nhs.uk
          location / {
               root   /usr/share/nginx/html;
               index  index.html index.htm;
               include /etc/nginx/mime.types;
               try_files $uri $uri/ /index.html$is_args$args;
          }
     }    
}

stream {
     server {
          listen 443;
          upstream docstore {
               server %DOC_STORE_API_ENDPOINT%/%BUILD_ENV%/Auth/BackChannelLogout
          }
          map $ssl_preread_server_name $upstream {
              access-request-fulfilment.patient-deductions.nhs.uk docstore;
          }
          proxy_ssl_server_name on;
          proxy_pass $upstream
          ssl_preread on;
     }
}