# .github/workflows/terraform-dev
name: 'Z-BASE Vitest Test: Run a vitest test job'

on:
  workflow_call:
    inputs:
      build_branch:
        description: 'Branch with smoke tests.'
        required: true
        type: 'string'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  vitest_testing_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'NHSDigital/national-document-repository'
          ref: ${{ github.event.inputs.build_branch }}
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure React environment vars
        env:
          ENDPOINT_DOC_STORE_API: http://localhost:3000
          AWS_REGION: test region
          OIDC_PROVIDER_ID: not provided yet
          IDENTITY_PROVIDER_POOL_ID: not provided yet
          MONITOR_ACCOUNT_ID: not provided yet          
          BUILD_ENV: development
          IMAGE_VERSION: 'ndr-not-required'
        run: |
          ./react-environment-config.sh
        working-directory: app
        shell: bash

      - run: make clean-install
      - run: make test-ui
