# .github/workflows/terraform-dev
name: "Z-BASE Cypress Smoketest: Smoketest shared actions for running"

on:
  workflow_call:
    inputs:
      build_branch:
        description: "Branch with smoke tests."
        required: true
        type: "string"
      environment:
        description: "Which Environment type are we using"
        required: true
        type: "string"
      sandbox:
        description: "Sandbox to run the smoke tests on."
        required: true
        type: "string"
    secrets:
      AWS_ASSUME_ROLE:
        required: true
      CYPRESS_ODSCODE:
        required: true
      CYPRESS_KEY:
        required: true

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: "NHSDigital/national-document-repository"
          ref: ${{ inputs.build_branch}}

      - name: AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          mask-aws-account-id: true
          aws-region: ${{ vars.AWS_REGION }}

      - name: Cypress install
        run: |
          npm install --legacy-peer-deps
        working-directory: ./app

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          working-directory: ./app
          spec: |
            cypress/e2e/1-ndr-smoke-tests/*.cy.js
            cypress/e2e/1-ndr-smoke-tests/**/*.cy.js
        env:
          CYPRESS_BASE_URL: "https://${{ inputs.sandbox }}.access-request-fulfilment.patient-deductions.nhs.uk"
          CYPRESS_grepTags: "smoke"
          CYPRESS_WORKSPACE: ${{ inputs.sandbox }}
          CYPRESS_ODSCODE: ${{ secrets.CYPRESS_ODSCODE }}
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_OUTPUT_VIDEO: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/national-document-repository/national-document-repository/app/cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: /home/runner/work/national-document-repository/national-document-repository/app/cypress/videos
          if-no-files-found: ignore

  cypress-run-edge:
    needs: ["cypress-run-chrome"]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: "NHSDigital/national-document-repository"
          ref: ${{ inputs.build_branch}}

      - name: AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Cypress install
        run: |
          npm install --legacy-peer-deps
        working-directory: ./app

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: edge
          working-directory: ./app
          spec: |
            cypress/e2e/1-ndr-smoke-tests/*.cy.js
            cypress/e2e/1-ndr-smoke-tests/**/*.cy.js
        env:
          CYPRESS_BASE_URL: "https://${{ inputs.sandbox }}.access-request-fulfilment.patient-deductions.nhs.uk"
          CYPRESS_grepTags: "smoke"
          CYPRESS_WORKSPACE: ${{ inputs.sandbox }}
          CYPRESS_ODSCODE: ${{ secrets.CYPRESS_ODSCODE }}
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_OUTPUT_VIDEO: false
